components/AIExplorer/ChatComponents/Interactions/Charts/BollingerBands.tsx
components/AIExplorer/ChatComponents/Interactions/Charts/LineChart.tsx
components/AIExplorer/ChatComponents/Interactions/Charts/MACDChart.tsx
components/AIExplorer/ChatComponents/Interactions/Charts/RSIChart.tsx
pages/ai-explorer/index.tsx

https://github.com/user-attachments/assets/502795bd-d66e-4cbd-9299-46e30d1c440f

fix: table/chart scrolling inside

---

pages/stake.tsx
services/api/user.ts

feat(api): update user rewards summary response type

---

abis/Compensate.json
components/Button/ConnectWalletButton.tsx
components/CompensationPlan/CompensationClaimTable.tsx
components/CompensationPlan/CompensationGuidePage.tsx
components/CompensationPlan/CompensationOverallCard.tsx
components/CompensationPlan/CompensationPlanPage.tsx
components/CompensationPlan/CompensationReleaseTable.tsx
components/CompensationPlan/CompenstationTable.tsx
components/Layout/Header/Header.tsx
constants/compensation_list.json
messages/en.json
messages/zh.json
pages/compensation-plan/index.tsx

完成了 UI/ i18n/权限问题/总览数据的读取等，等待两个 table 的接口。
env 新增：
```
NEXT_PUBLIC_COMPENSATION_ADDRESS=0xd3429eaE61F468Cfb35bbD70de5204AA712c025c
```
录屏如下（录屏中 mock 了部分处理）：
https://github.com/user-attachments/assets/8463419b-9dfb-4958-b7a7-9fcbae8ca684

Feat: Compensation Plan Page (等待 table 相关接口）

---

components/Modal/AcceleratePoolModal.tsx
services/api/staking.ts

feat: add staking apy summary

---

pages/stake.tsx

fix: staking effect issue

---

pages/stake.tsx

feat(stake): add pool b api request condition based on env flag

---

pages/stake.tsx
utils/currency.ts

fix(stake): adjust pool c text content

---

components/Modal/AcceleratePoolModal.tsx
messages/en.json
messages/zh.json
pages/stake.tsx

fix: staking modal i18n

---

pages/my-account/index.tsx

1. 新建账户，进入 https://dev.matrixlayer.ai/my-account 会出现 js报错

fix(my-account): resolve js error on account page initialization

---

components/Modal/RewardsPoolBHistoryModal.tsx
contexts/modal.tsx
messages/en.json
messages/zh.json
pages/stake.tsx
services/api/user.ts

feat(modal): add rewards history modal

---

components/Modal/RewardsPoolBHistoryModal.tsx
contexts/modal.tsx
messages/en.json
messages/zh.json
pages/stake.tsx
services/api/user.ts

feat(stake): add mlp rewards modal and integrate api fields

---

abis/StakeB.json
pages/stake.tsx
services/api/staking.ts

对接 stake pool b 新的合约
NEXT_PUBLIC_STAKE_B_ADDRESS=0x206c2490B76d7Fb22665333f97E4BB13E8948995
NEXT_PUBLIC_STAKE_C_ADDRESS=0xfe11485ec993D2546A8fF277Bfa669D72f063505

feat(stake): integrate new stake b1 api

---

services/axios/client.ts

fix: add api error toast

---

pages/stake.tsx

fix(stake): update poolc staking amount display

---

components/Modal/RewardsPoolBHistoryModal.tsx
pages/stake.tsx

feat(stake): add pool a history modal

---

abis/Payment.json

NEXT_PUBLIC_PAYMENT_ADDRESS=0xa0e5E63C517aA36b301c148d46d7302965D80BB1

chore(payment): update payment address

---

components/Modal/RewardsPoolBHistoryModal.tsx
pages/stake.tsx
utils/currency.ts

feat(utils): add formatForMatrix logic for currency formatting

---

pages/stake.tsx
types/api.ts

如果 有 merchantAddress, 就 隐藏 claim 按钮

fix: hide claim button in user stake page

---

components/Modal/RewardsModal.tsx
messages/en.json
messages/zh.json
services/api/user.ts

feat(rewards): add reward history list functionality

---

components/Modal/RewardsModal.tsx

fix(rewards): resolve pagination issues in rewards modal

---

messages/zh.json
pages/stake.tsx

fix: balance number

---

components/Modal/ConnectWalletModal.tsx

fix(wallet): correct styles for light mode display
